import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { readLibOpenMPTSources } from './helpers/libOpenMPTSource';
import { readAudioGraphSources } from './helpers/audioGraphSource';
import {
  MAIN_TO_WORKLET,
  WORKLET_TO_MAIN,
  ALL_MAIN_TO_WORKLET_TYPES,
  ALL_WORKLET_TO_MAIN_TYPES,
} from '../audio-worklet/workletProtocolConstants';
import {
  parseMainToWorkletMessage,
  parseOscBufferMessage,
  parseWorkletToMainMessage,
  postLoad,
  postPlay,
  postSeek,
  postSetProjectmPcm,
  postSetChannelMute,
  postSetRenderParam,
  postCtlSetText,
} from '../audio-worklet/protocol';
import { AUDIO_SAB_BYTES } from '../utils/audioReactive';

const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));

const GENERATED_WORKLET = join(ROOT, 'public/worklets/openmpt-worklet.js');
const GENERATED_BRIDGE = join(ROOT, 'public/worklets/native-bridge-processor.js');

describe('workletProtocol constants parity', () => {
  it('generated worklet inlines the canonical constants (no hand-mirrored copy)', () => {
    const worklet = readFileSync(GENERATED_WORKLET, 'utf8');
    // The classic bootstrap that had to be kept in sync by hand is gone —
    // esbuild compiles workletProtocolConstants.ts straight into the bundle.
    expect(existsSync(join(ROOT, 'public/worklets/worklet-protocol-constants.js'))).toBe(false);

    for (const [key, value] of Object.entries(MAIN_TO_WORKLET)) {
      expect(worklet, `MAIN_TO_WORKLET.${key}`).toContain(`${key}: "${value}"`);
    }
    for (const [key, value] of Object.entries(WORKLET_TO_MAIN)) {
      expect(worklet, `WORKLET_TO_MAIN.${key}`).toContain(`${key}: "${value}"`);
    }
  });

  it('generated worklets are current with their TypeScript sources', () => {
    // Same gate as `npm run verify:worklet-js`: a hand-edit of the public file,
    // or a forgotten rebuild after editing src/worklets/**, fails here.
    expect(() =>
      execFileSync('node', ['scripts/build-worklet-js.mjs', '--check'], {
        cwd: ROOT,
        stdio: 'pipe',
      }),
    ).not.toThrow();
  });

  it('generated worklets are marked GENERATED and name their source', () => {
    const worklet = readFileSync(GENERATED_WORKLET, 'utf8');
    const bridge = readFileSync(GENERATED_BRIDGE, 'utf8');
    expect(worklet).toContain('@generated by scripts/build-worklet-js.mjs');
    expect(worklet).toContain('src/worklets/openmpt-processor.ts');
    expect(bridge).toContain('@generated by scripts/build-worklet-js.mjs');
    expect(bridge).toContain('src/worklets/native-bridge.ts');
  });

  it('main→worklet guard has a single implementation shared with the worklet', () => {
    const worklet = readFileSync(GENERATED_WORKLET, 'utf8');
    const protocol = readFileSync(join(ROOT, 'audio-worklet/protocol.ts'), 'utf8');
    // protocol.ts re-exports the zero-dependency guard instead of a second
    // zod schema — adding a message type is one edit, not two.
    expect(protocol).toMatch(/from '\.\/mainToWorkletMessages'/);
    expect(protocol).not.toContain('mainToWorkletMessageSchema');
    // ...and the worklet bundles that same function (zod never reaches the audio thread).
    expect(worklet).toContain('function parseMainToWorkletMessage');
    expect(worklet).not.toContain('zod');
  });

  it('hooks import protocol helpers instead of raw type literals', () => {
    const useAudioGraph = readAudioGraphSources(ROOT);
    const useLibOpenMPT = readLibOpenMPTSources(ROOT);
    expect(useAudioGraph).toMatch(/from ['"].*audio-worklet\/protocol['"]/);
    expect(useAudioGraph).toContain('parseWorkletToMainMessageOrWarn');
    expect(useAudioGraph).toContain('dispatchWorkletToMainMessage');
    expect(useLibOpenMPT).toContain('parseOscBufferMessage');
    expect(useLibOpenMPT).not.toMatch(/as SharedArrayBuffer/);
  });

  it('worklet routes messages through the shared constants', () => {
    const worklet = readFileSync(GENERATED_WORKLET, 'utf8');
    expect(worklet).toContain('parseMainToWorklet');
    expect(worklet).toContain('WT.position');
    expect(worklet).toContain('MT.load');
  });

  it('nothing still addModule()s the removed protocol bootstrap', () => {
    const startJs = readFileSync(join(ROOT, 'hooks/audioGraph/startJsWorkletPlayback.ts'), 'utf8');
    expect(startJs).not.toContain('worklet-protocol-constants');
  });
});

describe('parseWorkletToMainMessage', () => {
  it('accepts a valid position message', () => {
    const parsed = parseWorkletToMainMessage({
      type: WORKLET_TO_MAIN.position,
      order: 1,
      row: 8,
      positionSeconds: 12.5,
      bpm: 125,
      channelVU: [0.1, 0.2],
    });
    expect(parsed.ok).toBe(true);
    if (parsed.ok && parsed.message.type === WORKLET_TO_MAIN.position) {
      expect(parsed.message.order).toBe(1);
    }
  });

  it('rejects malformed position messages', () => {
    const parsed = parseWorkletToMainMessage({
      type: WORKLET_TO_MAIN.position,
      order: 'bad',
      row: 0,
      positionSeconds: 1,
      bpm: 125,
    });
    expect(parsed.ok).toBe(false);
  });

  it('rejects unknown message types', () => {
    const parsed = parseWorkletToMainMessage({ type: 'totally-unknown', foo: 1 });
    expect(parsed.ok).toBe(false);
  });

  it('validates oscBuffer SharedArrayBuffer size', () => {
    const smallSab = new SharedArrayBuffer(8);
    const parsed = parseWorkletToMainMessage({
      type: WORKLET_TO_MAIN.oscBuffer,
      buffer: smallSab,
    });
    expect(parsed.ok).toBe(false);

    const validSab = new SharedArrayBuffer(AUDIO_SAB_BYTES);
    const ok = parseWorkletToMainMessage({
      type: WORKLET_TO_MAIN.oscBuffer,
      buffer: validSab,
    });
    expect(ok.ok).toBe(true);
    expect(parseOscBufferMessage({ type: WORKLET_TO_MAIN.oscBuffer, buffer: validSab })).not.toBeNull();
  });

  it('accepts loaded / ended / seekAck / error variants', () => {
    expect(parseWorkletToMainMessage({ type: WORKLET_TO_MAIN.loaded }).ok).toBe(true);
    expect(parseWorkletToMainMessage({ type: WORKLET_TO_MAIN.ended }).ok).toBe(true);
    expect(parseWorkletToMainMessage({ type: WORKLET_TO_MAIN.seekAck }).ok).toBe(true);
    expect(
      parseWorkletToMainMessage({ type: WORKLET_TO_MAIN.error, message: 'boom' }).ok,
    ).toBe(true);
  });
});

describe('parseMainToWorkletMessage', () => {
  it('accepts typed outbound helpers', () => {
    const buf = new Uint8Array([1, 2, 3]);
    expect(parseMainToWorkletMessage(postPlay()).ok).toBe(true);
    expect(parseMainToWorkletMessage(postLoad(buf)).ok).toBe(true);
    expect(parseMainToWorkletMessage(postSeek(2, 16, 1.5)).ok).toBe(true);
    expect(parseMainToWorkletMessage(postSetProjectmPcm(true)).ok).toBe(true);
    expect(parseMainToWorkletMessage(postSetProjectmPcm(false)).ok).toBe(true);
    expect(parseMainToWorkletMessage(postSetChannelMute(0, true)).ok).toBe(true);
    expect(parseMainToWorkletMessage(postSetRenderParam(3, 8)).ok).toBe(true);
    expect(parseMainToWorkletMessage(postCtlSetText('play.at_end', 'continue')).ok).toBe(true);
  });

  it('rejects malformed setProjectmPcm', () => {
    expect(parseMainToWorkletMessage({ type: MAIN_TO_WORKLET.setProjectmPcm }).ok).toBe(false);
    expect(
      parseMainToWorkletMessage({ type: MAIN_TO_WORKLET.setProjectmPcm, enabled: 'yes' }).ok,
    ).toBe(false);
  });

  it('rejects malformed load payloads', () => {
    expect(parseMainToWorkletMessage({ type: MAIN_TO_WORKLET.load }).ok).toBe(false);
    expect(parseMainToWorkletMessage({ type: MAIN_TO_WORKLET.seek, order: -1, row: 0 }).ok).toBe(false);
    expect(parseMainToWorkletMessage({ type: MAIN_TO_WORKLET.setChannelMute, channel: 0 }).ok).toBe(false);
    expect(parseMainToWorkletMessage({ type: MAIN_TO_WORKLET.ctlSetText, key: 'x' }).ok).toBe(false);
  });

  it('covers every declared message type string', () => {
    expect(ALL_MAIN_TO_WORKLET_TYPES.length).toBeGreaterThan(0);
    expect(ALL_WORKLET_TO_MAIN_TYPES.length).toBeGreaterThan(0);
    for (const t of ALL_MAIN_TO_WORKLET_TYPES) {
      expect(typeof t).toBe('string');
    }
    for (const t of ALL_WORKLET_TO_MAIN_TYPES) {
      expect(typeof t).toBe('string');
    }
  });
});
