// ============================================================
// patternv0.54_neon.wgsl
//
// GENERATED by scripts/build-shaders.mjs — DO NOT EDIT DIRECTLY.
// Source: shaders/src/patternv0.54_neon.wgsl
//
// To regenerate:
//   npm run build:shaders
// ============================================================

// ============================================================
// patternv0.54_neon.wgsl — Source file
// Neon Night — Dark background with cyan & magenta neon accents
//
// Evolves v0.53_midnight by adding:
//   • Subtle neon grid lines (cyan vertical, magenta horizontal)
//   • Neon rim light on housing borders
//   • Cyan/magenta alternating expression lights
//   • Neon-tinted bloom bleed (colour varies by channel position)
//   • Soft neon scanline overlay
//   • Electric playhead ring with dual-colour pulse
//
// Assembled via build-shaders.mjs from:
//   #include "common.wgsl"
//   #include "sdf_primitives.wgsl"
//   #include "color_palettes.wgsl"
//   #include "note_parsing.wgsl"
//   #include "bloom_effects.wgsl"
//   #include "led_drawing.wgsl"
// ============================================================

// >>> begin include "common.wgsl"  (shaders/include/common.wgsl)
// #pragma once  (shaders/include/common.wgsl)
// ============================================================
// common.wgsl — Shared uniforms, structs, bindings, and
//               circular vertex shader for classic pattern shaders.
//
// Include this FIRST. It defines Uniforms, bindings, VertexOut,
// and the circular-layout vertex stage. Pure math utilities
// (SDFs, palettes) have been moved to dedicated includes.
// ============================================================

// ── Math Constants ──
const PI: f32 = 3.14159265;
const TAU: f32 = 6.2831853;
const PI_HALF: f32 = 1.570796;

// ── Note Range Constants ──
const NOTE_MIN: u32 = 1u;
const NOTE_MAX: u32 = 119u;
const NOTE_OFF_MIN: u32 = 120u;

// ── Shared Color Constants ──
/// Near-black used for dead / empty / expression-only cells.
const DEAD_COLOR: vec3<f32> = vec3<f32>(0.051, 0.051, 0.051);

/// Dark glass background used inside lens caps and housing.
const GLASS_BG: vec3<f32> = vec3<f32>(0.04, 0.04, 0.05);

/// Unlit diode housing color.
const DIODE_HOUSING: vec3<f32> = vec3<f32>(0.06, 0.06, 0.08);

// ── Uniforms ──
struct Uniforms {
  numRows: u32,
  numChannels: u32,
  playheadRow: f32,
  isPlaying: u32,
  cellW: f32,
  cellH: f32,
  canvasW: f32,
  canvasH: f32,
  tickOffset: f32,
  bpm: f32,
  timeSec: f32,
  beatPhase: f32,
  groove: f32,
  kickTrigger: f32,
  activeChannels: u32,
  isModuleLoaded: u32,
  bloomIntensity: f32,
  bloomThreshold: f32,
  invertChannels: u32,
  dimFactor: f32,
  _r0: f32,
  _r1: f32,
  _r2: f32,
  _r3: f32,
  colorPalette: u32,
};

// ── Storage & Uniform Bindings ──
@group(0) @binding(0) var<storage, read> cells: array<u32>;
@group(0) @binding(1) var<uniform> uniforms: Uniforms;
@group(0) @binding(2) var<storage, read> rowFlags: array<u32>;

struct ChannelState {
  volume: f32,
  pan: f32,
  freq: f32,
  trigger: u32,
  noteAge: f32,
  activeEffect: u32,
  effectValue: f32,
  isMuted: u32
};
@group(0) @binding(3) var<storage, read> channels: array<ChannelState>;

@group(0) @binding(4) var buttonsSampler: sampler;
@group(0) @binding(5) var buttonsTexture: texture_2d<f32>;

// ── Vertex I/O ──
struct VertexOut {
  @builtin(position) position: vec4<f32>,
  @location(0) @interpolate(flat) row: u32,
  @location(1) @interpolate(flat) channel: u32,
  @location(2) @interpolate(linear) uv: vec2<f32>,
  @location(3) @interpolate(flat) packedA: u32,
  @location(4) @interpolate(flat) packedB: u32,
};

// ── Vertex Shader ──
/// Circular ring layout: each cell becomes a rotated quad positioned
/// radially according to its channel (ring index) and row (angle).
/// Channel 0 is reserved for the indicator ring when padTopChannel=true.
@vertex
fn vs(@builtin(vertex_index) vertexIndex: u32, @builtin(instance_index) instanceIndex: u32) -> VertexOut {
  var quad = array<vec2<f32>, 6>(
    vec2<f32>(0.0, 0.0), vec2<f32>(1.0, 0.0), vec2<f32>(0.0, 1.0),
    vec2<f32>(0.0, 1.0), vec2<f32>(1.0, 0.0), vec2<f32>(1.0, 1.0)
  );

  let numChannels = uniforms.numChannels;
  let row = instanceIndex / numChannels;
  let channel = instanceIndex % numChannels;

  let invertedChannel = numChannels - 1u - channel;
  let ringIndex = select(invertedChannel, channel, (uniforms.invertChannels == 1u));

  let center = vec2<f32>(uniforms.canvasW * 0.5, uniforms.canvasH * 0.5);
  let minDim = min(uniforms.canvasW, uniforms.canvasH);

  let maxRadius = minDim * 0.45;
  let minRadius = minDim * 0.15;
  let ringDepth = (maxRadius - minRadius) / f32(numChannels);

  let radius = minRadius + f32(ringIndex) * ringDepth;

  let totalSteps = f32(uniforms.numRows);
  let anglePerStep = TAU / totalSteps;
  let theta = -PI_HALF + f32(row % uniforms.numRows) * anglePerStep;

  let circumference = 2.0 * PI * radius;
  let arcLength = circumference / totalSteps;

  let btnW = arcLength * 0.95;
  let btnH = ringDepth * 0.95;

  let lp = quad[vertexIndex];
  let localPos = (lp - 0.5) * vec2<f32>(btnW, btnH);

  let rotAng = theta + PI_HALF;
  let cA = cos(rotAng);
  let sA = sin(rotAng);

  let rotX = localPos.x * cA - localPos.y * sA;
  let rotY = localPos.x * sA + localPos.y * cA;

  let worldX = center.x + cos(theta) * radius + rotX;
  let worldY = center.y + sin(theta) * radius + rotY;

  let clipX = (worldX / uniforms.canvasW) * 2.0 - 1.0;
  let clipY = 1.0 - (worldY / uniforms.canvasH) * 2.0;

  // High-precision packing: two u32s per cell (PackedA + PackedB)
  let idx = instanceIndex * 2u;
  let a = cells[idx];
  let b = cells[idx + 1u];

  var out: VertexOut;
  out.position = vec4<f32>(clipX, clipY, 0.0, 1.0);
  out.row = row;
  out.channel = channel;
  out.uv = lp;
  out.packedA = a;
  out.packedB = b;
  return out;
}

// ── Include helpers (move to dedicated includes) ──
//   sdf_primitives.wgsl  — sdRoundedBox, sdCircle, sdEllipse
//   color_palettes.wgsl  — selectPalette, neonPalette, pitchClassFromIndex

// <<< end include "common.wgsl"  (shaders/include/common.wgsl)
// >>> begin include "sdf_primitives.wgsl"  (shaders/include/sdf_primitives.wgsl)
// #pragma once  (shaders/include/sdf_primitives.wgsl)
// ============================================================
// sdf_primitives.wgsl — Signed-distance field primitives.
//
// Include AFTER common.wgsl or bloom/core.wgsl.
// No bindings or uniforms are declared here.
// ============================================================

/// Signed distance to a rounded rectangle.
fn sdRoundedBox(p: vec2<f32>, b: vec2<f32>, r: f32) -> f32 {
  let q = abs(p) - b + r;
  return length(max(q, vec2<f32>(0.0))) + min(max(q.x, q.y), 0.0) - r;
}

/// Signed distance to a circle.
fn sdCircle(p: vec2<f32>, r: f32) -> f32 {
  return length(p) - r;
}

/// Signed distance to an ellipse.
fn sdEllipse(p: vec2<f32>, ab: vec2<f32>) -> f32 {
  let k = length(p / ab);
  return (k - 1.0) * min(ab.x, ab.y);
}

/// Signed distance to an axis-aligned box.
fn sdBox(p: vec2<f32>, b: vec2<f32>) -> f32 {
  let d = abs(p) - b;
  return length(max(d, vec2<f32>(0.0))) + min(max(d.x, d.y), 0.0);
}

/// Signed distance to an equilateral triangle (pointing up).
fn sdTriangle(p: vec2<f32>, r: f32) -> f32 {
  let k = sqrt(3.0);
  var p2 = p;
  p2.x = abs(p2.x) - r;
  p2.y = p2.y + r / k;
  if (p2.x + k * p2.y > 0.0) { p2 = vec2<f32>(p2.x - k * p2.y, -k * p2.x - p2.y) / 2.0; }
  p2.x = p2.x - clamp(p2.x, -2.0 * r, 0.0);
  return -length(p2) * sign(p2.y);
}

// <<< end include "sdf_primitives.wgsl"  (shaders/include/sdf_primitives.wgsl)
// >>> begin include "color_palettes.wgsl"  (shaders/include/color_palettes.wgsl)
// #pragma once  (shaders/include/color_palettes.wgsl)
// ============================================================
// color_palettes.wgsl — Color palette and pitch-class helpers.
//
// Include AFTER common.wgsl or bloom/core.wgsl (needs TAU).
// ============================================================

/// Select a color palette by ID (0–4). All palettes use the same
/// cosine gradient basis with different phase offsets.
fn selectPalette(id: u32, t: f32) -> vec3<f32> {
  let a = vec3<f32>(0.5, 0.5, 0.5);
  let b = vec3<f32>(0.5, 0.5, 0.5);
  let c = vec3<f32>(1.0, 1.0, 1.0);
  if (id == 1u) {
    // Warm: reds, oranges, yellows
    return a + b * cos(TAU * (c * t + vec3<f32>(0.0, 0.1, 0.2)));
  } else if (id == 2u) {
    // Cool: blues, cyans, purples
    return a + b * cos(TAU * (c * t + vec3<f32>(0.5, 0.7, 0.9)));
  } else if (id == 3u) {
    // Neon: pink, cyan, green
    return a + b * cos(TAU * (c * t + vec3<f32>(0.0, 0.5, 1.0)));
  } else if (id == 4u) {
    // Acid: green, yellow, chartreuse
    return a + b * cos(TAU * (c * t + vec3<f32>(0.3, 0.0, 0.7)));
  }
  // Default palette 0: Rainbow
  return a + b * cos(TAU * (c * t + vec3<f32>(0.0, 0.33, 0.67)));
}

/// Classic rainbow cosine gradient. Equivalent to selectPalette(0u, t).
fn neonPalette(t: f32) -> vec3<f32> {
  return selectPalette(0u, t);
}

/// Map a tracker note index (1–119) to a pitch-class hue [0,1).
fn pitchClassFromIndex(note: u32) -> f32 {
  if (note == 0u || note >= NOTE_OFF_MIN) { return 0.0; }
  let semi = (note - 1u) % 12u;
  return f32(semi) / 12.0;
}

// <<< end include "color_palettes.wgsl"  (shaders/include/color_palettes.wgsl)
// >>> begin include "note_parsing.wgsl"  (shaders/include/note_parsing.wgsl)
// #pragma once  (shaders/include/note_parsing.wgsl)
// ============================================================
// note_parsing.wgsl — Note and effect parsing helpers.
//
// Include AFTER common.wgsl or bloom/core.wgsl.
// ============================================================

/// Convert an ASCII character to uppercase (A–Z / a–z only).
fn toUpperAscii(code: u32) -> u32 {
  if (code >= 97u && code <= 122u) {
    return code - 32u;
  }
  return code;
}

/// Map an ASCII-packed note representation to a pitch-class hue [0,1).
/// Used by high-precision shaders where the note is stored as ASCII
/// characters in the upper bytes of packedA.
fn pitchClassFromPacked(packed: u32) -> f32 {
  let c0 = toUpperAscii((packed >> 24) & 255u);
  var semitone: i32 = 0;
  var valid = true;
  switch (c0) {
    case 65u: { semitone = 9; }   // A
    case 66u: { semitone = 11; }  // B
    case 67u: { semitone = 0; }   // C
    case 68u: { semitone = 2; }   // D
    case 69u: { semitone = 4; }   // E
    case 70u: { semitone = 5; }   // F
    case 71u: { semitone = 7; }   // G
    default: { valid = false; }
  }
  if (!valid) { return 0.0; }
  let c1 = toUpperAscii((packed >> 16) & 255u);
  if ((c1 == 35u) || (c1 == 43u)) {        // # or +
    semitone = (semitone + 1) % 12;
  } else if (c1 == 66u) {                  // b (flat)
    semitone = (semitone + 11) % 12;
  }
  return f32(semitone) / 12.0;
}

/// Convert an effect command code (ASCII) to a tinted color.
fn effectColorFromCode(code: u32, fallback: vec3<f32>) -> vec3<f32> {
  let c = toUpperAscii(code & 255u);
  switch c {
    case 49u: { return mix(fallback, vec3<f32>(0.2, 0.85, 0.4), 0.75); } // 1xx Porta Up — Green
    case 50u: { return mix(fallback, vec3<f32>(0.85, 0.3, 0.3), 0.75); } // 2xx Porta Down — Red
    case 52u: { return mix(fallback, vec3<f32>(0.4, 0.7, 1.0), 0.6); }  // 4xx Vibrato — Blue
    case 55u: { return mix(fallback, vec3<f32>(0.9, 0.6, 0.2), 0.6); }  // 7xx Tremolo — Orange
    case 65u: { return mix(fallback, vec3<f32>(0.95, 0.9, 0.25), 0.7); } // Axx VolSlide — Yellow
    default:  { return fallback; }
  }
}

// <<< end include "note_parsing.wgsl"  (shaders/include/note_parsing.wgsl)
// >>> begin include "bloom_effects.wgsl"  (shaders/include/bloom_effects.wgsl)
// #pragma once  (shaders/include/bloom_effects.wgsl)
// ============================================================
// bloom_effects.wgsl — Bloom intensity curves, glow kernels,
// kick-reactive flash, and film-grain dither.
//
// Include AFTER common.wgsl or bloom/core.wgsl.
// ============================================================

/// High-intensity boost: base + bloom * 2.0
fn bloomBoost(base: f32, bloom: f32) -> f32 {
  return base + bloom * 2.0;
}

/// Medium boost: base + bloom * 1.0
fn bloomBoostMedium(base: f32, bloom: f32) -> f32 {
  return base + bloom * 1.0;
}

/// Soft ambient boost: base + bloom * 0.2
fn bloomSoft(base: f32, bloom: f32) -> f32 {
  return base + bloom * 0.2;
}

/// Exponential radial glow kernel.
fn pointGlow(p: vec2<f32>, color: vec3<f32>, intensity: f32, falloff: f32) -> vec3<f32> {
  return color * intensity * exp(-length(p) * falloff);
}

/// Kick-reactive magenta bloom flash.
fn kickReactiveGlow(p: vec2<f32>, kick: f32, bloom: f32) -> vec3<f32> {
  let kickPulse = kick * exp(-length(p) * 3.0) * 0.3;
  return vec3<f32>(0.9, 0.2, 0.4) * kickPulse * bloom;
}

/// Film-grain dither to reduce banding in dark regions.
fn ditherNoise(uv: vec2<f32>, time: f32) -> f32 {
  let noise = fract(sin(dot(uv * time, vec2<f32>(12.9898, 78.233))) * 43758.5453);
  return (noise - 0.5) * 0.01;
}

// <<< end include "bloom_effects.wgsl"  (shaders/include/bloom_effects.wgsl)
// >>> begin include "led_drawing.wgsl"  (shaders/include/led_drawing.wgsl)
// #pragma once  (shaders/include/led_drawing.wgsl)
// ============================================================
// led_drawing.wgsl — LED emitter and lens-cap drawing primitives.
//
// Include AFTER sdf_primitives.wgsl and common.wgsl / bloom/core.wgsl.
// Defines FragmentConstants, multiple lens styles, and the chrome
// dome indicator shared across classic and bloom families.
// ============================================================

// ── Fragment Constants ──

struct FragmentConstants {
  bgColor: vec3<f32>,
  ledOnColor: vec3<f32>,
  ledOffColor: vec3<f32>,
  borderColor: vec3<f32>,
  housingSize: vec2<f32>,
};

/// Blue/Orange trap palette: primary indicator is warm orange.
fn getFragmentConstants() -> FragmentConstants {
  var c: FragmentConstants;
  c.bgColor = GLASS_BG;
  c.ledOnColor = vec3<f32>(1.0, 0.55, 0.1);
  c.ledOffColor = DIODE_HOUSING;
  c.borderColor = vec3<f32>(0.0, 0.0, 0.0);
  c.housingSize = vec2<f32>(0.92, 0.92);
  return c;
}

/// Cyan/Teal chrome palette from the v0.35 bloom family.
fn getBloomFragmentConstants() -> FragmentConstants {
  var c: FragmentConstants;
  c.bgColor = vec3<f32>(0.15, 0.16, 0.18);
  c.ledOnColor = vec3<f32>(0.0, 0.85, 0.95);
  c.ledOffColor = vec3<f32>(0.08, 0.08, 0.10);
  c.borderColor = vec3<f32>(0.0, 0.0, 0.0);
  c.housingSize = vec2<f32>(0.92, 0.92);
  return c;
}

// ── Emitter Diode Shape ──

/// Draw a single LED emitter (rounded box die + housing).
/// Returns RGBA where alpha is the diode mask.
fn drawEmitterDiode(uv: vec2<f32>, intensity: f32, color: vec3<f32>, isOn: bool) -> vec4<f32> {
  let diodeSize = vec2<f32>(0.28, 0.14);

  let p = uv;
  let dDiode = sdRoundedBox(p, diodeSize * 0.5, 0.06);

  // Smaller "die" inside the diode for a distinct dot appearance
  let dieSize = vec2<f32>(0.10, 0.05);
  let dDie = sdRoundedBox(p, dieSize * 0.5, 0.02);

  let diodeMask = 1.0 - smoothstep(0.0, 0.015, dDiode);
  let dieMask = 1.0 - smoothstep(0.0, 0.008, dDie);

  var diodeColor = DIODE_HOUSING;

  if (isOn) {
    let dieGlow = color * (1.0 + intensity * 4.0);
    let housingGlow = color * 0.12 * intensity;
    diodeColor = mix(housingGlow, dieGlow, dieMask);
    let hotspot = exp(-length(p / vec2<f32>(0.06, 0.03)) * 2.5) * intensity;
    diodeColor += color * hotspot * 0.6;
  }

  return vec4<f32>(diodeColor, diodeMask);
}

// ── Unified Three-Emitter Lens Cap ──

/// Single glass surface covering three vertical emitters (top, mid, bot).
/// Creates optical effects: refraction, fresnel reflection, subsurface
/// scattering, and per-emitter fringe glow.
fn drawUnifiedLensCap(
    uv: vec2<f32>,
    lensSize: vec2<f32>,
    topEmitter: vec4<f32>,    // rgb=color, a=intensity (Blue note-on)
    midEmitter: vec4<f32>,    // rgb=color, a=intensity (Note color)
    botEmitter: vec4<f32>,    // rgb=color, a=intensity (Amber control)
    aa: f32
) -> vec4<f32> {
  let p = uv;
  let dBox = sdRoundedBox(p, lensSize * 0.5, 0.12);

  if (dBox > 0.0) {
    return vec4<f32>(0.0);
  }

  // Emitter positions under the lens (vertical arrangement)
  let topPos = vec2<f32>(0.0, -0.28);
  let midPos = vec2<f32>(0.0, 0.0);
  let botPos = vec2<f32>(0.0, 0.28);

  // Glass surface properties
  let radial = length(p / (lensSize * 0.5));
  let edgeThickness = 0.18 + radial * 0.12;
  let centerThickness = 0.06;
  let thickness = mix(centerThickness, edgeThickness, radial * radial);

  let n = normalize(vec3<f32>(p.x * 2.5 / lensSize.x, p.y * 2.5 / lensSize.y, 0.35));
  let viewDir = vec3<f32>(0.0, 0.0, 1.0);
  let fresnel = pow(1.0 - abs(dot(n, viewDir)), 2.5);

  // Draw individual emitters under the lens
  let topDiode = drawEmitterDiode(uv - topPos, topEmitter.a, topEmitter.rgb, topEmitter.a > 0.05);
  let midDiode = drawEmitterDiode(uv - midPos, midEmitter.a, midEmitter.rgb, midEmitter.a > 0.05);
  let botDiode = drawEmitterDiode(uv - botPos, botEmitter.a, botEmitter.rgb, botEmitter.a > 0.05);

  // Composite emitters back-to-front
  var combinedDiode = DIODE_HOUSING;
  if (botDiode.a > 0.0) {
    combinedDiode = mix(combinedDiode, botDiode.rgb, botDiode.a);
  }
  if (midDiode.a > 0.0) {
    combinedDiode = mix(combinedDiode, midDiode.rgb, midDiode.a);
  }
  if (topDiode.a > 0.0) {
    combinedDiode = mix(combinedDiode, topDiode.rgb, topDiode.a);
  }
  let diodeMask = max(max(topDiode.a, midDiode.a), botDiode.a);

  // Refraction offset
  let refractionStrength = (1.0 - radial * 0.6) * 0.04;
  let refractOffset = p * refractionStrength;

  // Subsurface scattering — per-emitter with tightened falloffs
  var subsurfaceGlow = vec3<f32>(0.0);

  let distTop = length(uv - topPos - refractOffset * 0.3);
  let scatterTop = exp(-distTop * 9.0) * topEmitter.a;
  subsurfaceGlow += topEmitter.rgb * scatterTop * 2.2;

  let distMid = length(uv - midPos - refractOffset * 0.5);
  let scatterMid = exp(-distMid * 7.5) * midEmitter.a;
  subsurfaceGlow += midEmitter.rgb * scatterMid * 3.0;

  let distBot = length(uv - botPos - refractOffset * 0.3);
  let scatterBot = exp(-distBot * 9.0) * botEmitter.a;
  subsurfaceGlow += botEmitter.rgb * scatterBot * 2.2;

  // Per-emitter fringe glow (replaces shared diffusion that smeared all three)
  subsurfaceGlow += topEmitter.rgb * exp(-distTop * 6.0) * topEmitter.a * 0.15;
  subsurfaceGlow += midEmitter.rgb * exp(-distMid * 6.0) * midEmitter.a * 0.15;
  subsurfaceGlow += botEmitter.rgb * exp(-distBot * 6.0) * botEmitter.a * 0.15;

  // Active color tint for the glass body
  var activeColor = midEmitter.rgb * midEmitter.a;
  activeColor = mix(activeColor, topEmitter.rgb, topEmitter.a * 0.5);
  activeColor = mix(activeColor, botEmitter.rgb, botEmitter.a * 0.5);

  let totalGlow = topEmitter.a + midEmitter.a + botEmitter.a;
  let litTint = mix(vec3<f32>(0.92, 0.93, 0.98), activeColor, min(totalGlow * 0.4, 0.4));
  let glassBaseColor = mix(GLASS_BG * 0.12, litTint, 0.88);

  // Edge alpha
  let edgeAlpha = smoothstep(0.0, aa * 2.0, -dBox);

  // Glass transparency
  let diodeVisibility = diodeMask * 0.55;
  let baseAlpha = 0.72 + 0.28 * fresnel;
  let alpha = mix(baseAlpha, 0.32, diodeVisibility) * edgeAlpha;

  // Directional lighting
  let lightDir = vec3<f32>(0.4, -0.7, 0.6);
  let diff = max(0.0, dot(n, normalize(lightDir)));
  let spec = pow(max(0.0, dot(reflect(-normalize(lightDir), n), viewDir)), 40.0);

  let litGlassColor = glassBaseColor * (0.45 + 0.55 * diff) + vec3<f32>(spec * 0.25);

  // Final composition
  var finalColor = GLASS_BG;

  let diodeBlend = diodeMask * (1.0 - alpha * 0.65);
  finalColor = mix(finalColor, combinedDiode, diodeBlend);
  finalColor = mix(finalColor, litGlassColor, alpha);
  finalColor += subsurfaceGlow * 1.8;

  // Concentrated glow halos around active emitters
  if (midEmitter.a > 0.05) {
    let midGlowDist = length(uv - midPos - refractOffset * 0.5);
    let midGlow = (1.0 - smoothstep(0.0, 0.18, midGlowDist)) * midEmitter.a * 0.5;
    finalColor += midEmitter.rgb * midGlow;
  }
  if (topEmitter.a > 0.05) {
    let topGlowDist = length(uv - topPos - refractOffset * 0.3);
    let topGlow = (1.0 - smoothstep(0.0, 0.14, topGlowDist)) * topEmitter.a * 0.3;
    finalColor += topEmitter.rgb * topGlow;
  }
  if (botEmitter.a > 0.05) {
    let botGlowDist = length(uv - botPos - refractOffset * 0.3);
    let botGlow = (1.0 - smoothstep(0.0, 0.14, botGlowDist)) * botEmitter.a * 0.3;
    finalColor += botEmitter.rgb * botGlow;
  }

  finalColor += fresnel * vec3<f32>(0.9, 0.95, 1.0) * 0.18 * (1.0 + radial * 0.5);

  // Horizontal separator shadows between emitter zones
  let sepShadowTop = (1.0 - smoothstep(0.0, 0.015, abs(p.y - (-0.14)))) * 0.35;
  let sepShadowBot = (1.0 - smoothstep(0.0, 0.015, abs(p.y - 0.14))) * 0.35;
  finalColor -= finalColor * (sepShadowTop + sepShadowBot);

  let vignette = 1.0 - radial * radial * 0.25;
  finalColor *= vignette;

  return vec4<f32>(finalColor, edgeAlpha);
}

// ── Frosted Glass Cap (single emitter) ──

/// Shows the diode shape underneath with proper translucency.
/// Used by v0.47 / v0.48 family shaders.
fn drawFrostedGlassCap(
    uv: vec2<f32>,
    size: vec2<f32>,
    color: vec3<f32>,
    isOn: bool,
    aa: f32,
    noteGlow: f32,
    diodeColor: vec3<f32>,
    diodeIntensity: f32
) -> vec4<f32> {
  let p = uv;
  let dBox = sdRoundedBox(p, size * 0.5, 0.08);

  if (dBox > 0.0) {
    return vec4<f32>(0.0);
  }

  // Draw the emitter diode underneath
  let diode = drawEmitterDiode(uv, diodeIntensity, diodeColor, isOn);

  // Glass surface normal for reflections
  let n = normalize(vec3<f32>(p.x * 2.0 / size.x, p.y * 2.0 / size.y, 0.4));
  let viewDir = vec3<f32>(0.0, 0.0, 1.0);
  let fresnel = pow(1.0 - abs(dot(n, viewDir)), 2.0);
  let radial = length(p / (size * 0.5));

  // Glass thickness varies - thicker at edges
  let edgeThickness = 0.15 + radial * 0.08;
  let centerThickness = 0.08;
  let thickness = mix(centerThickness, edgeThickness, radial);

  // Subsurface scattering - light travels through the glass
  let emitterPos = vec2<f32>(0.0, 0.22);
  let distFromEmitter = length(uv - emitterPos);
  let lightTravel = exp(-distFromEmitter * 4.0) * noteGlow;

  // Light concentrates upward from the emitter
  let upwardBias = smoothstep(0.0, -0.3, uv.y - emitterPos.y);
  let subsurface = lightTravel * upwardBias * (1.0 - radial * 0.3);

  // Glass tint varies with light passing through
  let litTint = mix(vec3<f32>(0.95, 0.95, 1.0), color, noteGlow * 0.3);
  let glassBaseColor = mix(GLASS_BG * 0.15, litTint, 0.85);

  // Edge alpha with anti-aliasing
  let edgeAlpha = smoothstep(0.0, aa * 2.0, -dBox);

  // Glass is more transparent where the diode is visible
  let diodeVisibility = diode.a * 0.6;
  let baseAlpha = 0.75 + 0.25 * fresnel;
  let alpha = mix(baseAlpha, 0.35, diodeVisibility) * edgeAlpha;

  // Directional lighting from top-left
  let lightDir = vec3<f32>(0.4, -0.7, 0.6);
  let diff = max(0.0, dot(n, normalize(lightDir)));
  let spec = pow(max(0.0, dot(reflect(-normalize(lightDir), n), viewDir)), 32.0);

  let litGlassColor = glassBaseColor * (0.5 + 0.5 * diff) + vec3<f32>(spec * 0.3);

  // Start with background
  var finalColor = GLASS_BG;

  // Layer the diode underneath
  let diodeBlend = diode.a * (1.0 - alpha * 0.7);
  finalColor = mix(finalColor, diode.rgb, diodeBlend);

  // Apply glass layer
  finalColor = mix(finalColor, litGlassColor, alpha);

  // Add subsurface glow from light passing through
  finalColor += subsurface * color * 2.5;

  // Inner glow when on - concentrated above the diode
  if (isOn) {
    let glowCenter = vec2<f32>(0.0, -0.1);
    let glowDist = length(uv - glowCenter);
    let innerGlow = (1.0 - smoothstep(0.0, 0.4, glowDist)) * noteGlow * 0.35;
    finalColor += color * innerGlow;
  }

  // Fresnel rim highlight
  finalColor += fresnel * vec3<f32>(0.9, 0.95, 1.0) * 0.15;

  return vec4<f32>(finalColor, edgeAlpha);
}

// ── Three-Emitter Lens (v0.49 style) ──

/// Three vertically-stacked emitters with a unified glass surface.
/// Slightly different optical model from drawUnifiedLensCap.
fn drawThreeEmitterLens(
  uv: vec2<f32>,
  size: vec2<f32>,
  topColor: vec3<f32>,
  topIntensity: f32,
  midColor: vec3<f32>,
  midIntensity: f32,
  botColor: vec3<f32>,
  botIntensity: f32,
  aa: f32
) -> vec4<f32> {
  let p = uv;
  let dBox = sdRoundedBox(p, size * 0.5, 0.08);

  if (dBox > 0.0) {
    return vec4<f32>(0.0);
  }

  // Emitter positions within the lens
  let topPos = vec2<f32>(0.0, -0.28);
  let midPos = vec2<f32>(0.0, 0.0);
  let botPos = vec2<f32>(0.0, 0.28);

  // Calculate distance to each emitter for light propagation
  let distTop = length(uv - topPos);
  let distMid = length(uv - midPos);
  let distBot = length(uv - botPos);

  // Glass surface normal for reflections
  let n = normalize(vec3<f32>(p.x * 2.0 / size.x, p.y * 2.0 / size.y, 0.4));
  let viewDir = vec3<f32>(0.0, 0.0, 1.0);
  let fresnel = pow(1.0 - abs(dot(n, viewDir)), 2.0);
  let radial = length(p / (size * 0.5));

  // Glass thickness varies - thicker at edges
  let edgeThickness = 0.15 + radial * 0.08;
  let centerThickness = 0.08;
  let thickness = mix(centerThickness, edgeThickness, radial);

  // Background
  let bgColor = GLASS_BG;

  // Calculate light contribution from each emitter
  let topGlow = exp(-distTop * 5.0) * topIntensity;
  let topDownwardBias = smoothstep(0.0, 0.4, uv.y - topPos.y);
  let topContribution = topGlow * topDownwardBias * topColor;

  let midGlow = exp(-distMid * 4.0) * midIntensity;
  let midContribution = midGlow * midColor;

  let botGlow = exp(-distBot * 5.0) * botIntensity;
  let botUpwardBias = smoothstep(0.0, 0.4, botPos.y - uv.y);
  let botContribution = botGlow * botUpwardBias * botColor;

  // Combine all light contributions
  var totalLight = vec3<f32>(0.0);
  totalLight += topContribution * 2.5;
  totalLight += midContribution * 3.0;
  totalLight += botContribution * 2.5;

  // Glass tint varies with light passing through
  var litTint = vec3<f32>(0.95, 0.95, 1.0);
  if (topIntensity > 0.0) { litTint = mix(litTint, topColor, topIntensity * 0.25); }
  if (midIntensity > 0.0) { litTint = mix(litTint, midColor, midIntensity * 0.3); }
  if (botIntensity > 0.0) { litTint = mix(litTint, botColor, botIntensity * 0.25); }

  let glassBaseColor = mix(bgColor * 0.15, litTint, 0.85);

  // Edge alpha with anti-aliasing
  let edgeAlpha = smoothstep(0.0, aa * 2.0, -dBox);

  // Glass alpha varies with emitter intensity (brighter = more transparent)
  let totalIntensity = topIntensity + midIntensity + botIntensity;
  let baseAlpha = 0.75 + 0.25 * fresnel;
  let alpha = mix(baseAlpha, 0.45, totalIntensity * 0.5) * edgeAlpha;

  // Directional lighting from top-left
  let lightDir = vec3<f32>(0.4, -0.7, 0.6);
  let diff = max(0.0, dot(n, normalize(lightDir)));
  let spec = pow(max(0.0, dot(reflect(-normalize(lightDir), n), viewDir)), 32.0);

  let litGlassColor = glassBaseColor * (0.5 + 0.5 * diff) + vec3<f32>(spec * 0.3);

  // Start with background
  var finalColor = bgColor;

  // Apply the combined light through the glass
  finalColor += totalLight * 0.8;

  // Apply glass layer
  finalColor = mix(finalColor, litGlassColor, alpha);

  // Add emitter hot spots where the actual LEDs are
  let topHotspot = exp(-distTop * 12.0) * topIntensity;
  let midHotspot = exp(-distMid * 10.0) * midIntensity;
  let botHotspot = exp(-distBot * 12.0) * botIntensity;

  finalColor += topColor * topHotspot * 1.5;
  finalColor += midColor * midHotspot * 1.2;
  finalColor += botColor * botHotspot * 1.5;

  // Fresnel rim highlight
  finalColor += fresnel * vec3<f32>(0.9, 0.95, 1.0) * 0.15;

  return vec4<f32>(finalColor, edgeAlpha);
}

// ── Chrome Dome Indicator ──

/// HDR chrome dome indicator with bezel, lens optics, and dimming support.
fn drawChromeIndicator(
    uv: vec2<f32>,
    size: vec2<f32>,
    color: vec3<f32>,
    isOn: bool,
    aa: f32,
    dimFactor: f32
) -> vec4<f32> {
  // Early-out bounding box for performance
  if (abs(uv.x) > size.x * 0.6 || abs(uv.y) > size.y * 0.6) {
    return vec4<f32>(0.0);
  }

  let uv01 = (uv / size) + vec2<f32>(0.5);
  let lensR = 0.7;
  let bezelR = 0.9;
  let center = vec2<f32>(0.5, 0.5);
  let dist = length(uv01 - center) * 2.0;

  var col = vec3<f32>(0.0);
  var alpha = 0.0;

  if (dist < bezelR) {
    if (dist > lensR) {
      // Bezel ring
      let angle = atan2(uv01.y - center.y, uv01.x - center.x);
      let rim = 0.2 + 0.8 * abs(sin(angle * 10.0));
      col = vec3<f32>(0.25, 0.28, 0.30) * rim * dimFactor;
      alpha = 1.0;
    } else {
      // Glass lens
      let lensNormR = dist / lensR;
      let z = sqrt(max(0.0, 1.0 - lensNormR * lensNormR));
      let localXY = (uv01 - center) / lensR;
      let normal = normalize(vec3<f32>(localXY.x, localXY.y, z));
      let lightDir = normalize(vec3<f32>(-0.5, 0.5, 1.0));
      let diffuse = max(0.0, dot(normal, lightDir));
      let reflectDir = reflect(-lightDir, normal);
      let specular = pow(max(0.0, dot(reflectDir, vec3<f32>(0.0, 0.0, 1.0))), 10.0);

      let baseColor = color * dimFactor;
      col = baseColor * (0.5 + 0.8 * diffuse);
      col += vec3<f32>(1.0) * specular * 0.5 * dimFactor;

      // Inner bloom rim glow
      let rimGlow = exp(-pow(lensNormR, 2.0) * 6.0);
      col += baseColor * rimGlow * 0.25;
      alpha = 1.0;
    }
  } else {
    return vec4<f32>(vec3<f32>(0.0), 0.0);
  }

  let vignette = smoothstep(bezelR * 0.95, bezelR, dist);
  col = mix(col * (1.0 - 0.08 * vignette), vec3<f32>(0.02) * dimFactor, vignette);

  return vec4<f32>(col, alpha);
}

// <<< end include "led_drawing.wgsl"  (shaders/include/led_drawing.wgsl)

// ═══════════════════════════════════════════════════════════
// NEON PALETTE & CONSTANTS
// ═══════════════════════════════════════════════════════════

/// Pitch-black studio base.
const NEON_BLACK: vec3<f32> = vec3<f32>(0.004, 0.004, 0.007);

/// Core neon accent colours.
const NEON_CYAN: vec3<f32>    = vec3<f32>(0.00, 0.90, 1.00);
const NEON_MAGENTA: vec3<f32> = vec3<f32>(1.00, 0.20, 0.75);
const NEON_AMBER: vec3<f32>   = vec3<f32>(1.00, 0.75, 0.05);

/// Desaturated neon for subtle ambient touches.
const CYAN_DIM: vec3<f32>    = vec3<f32>(0.02, 0.25, 0.30);
const MAGENTA_DIM: vec3<f32> = vec3<f32>(0.30, 0.05, 0.20);

// ═══════════════════════════════════════════════════════════
// NEON ATMOSPHERE FUNCTIONS
// ═══════════════════════════════════════════════════════════

/// Slow dual-phase breathing for neon pulse.
fn neonBreathe(time: f32) -> vec2<f32> {
  let t1 = sin(time * 1.6);
  let t2 = sin(time * 2.1 + 1.047);
  return vec2<f32>(0.88 + 0.12 * t1, 0.88 + 0.12 * t2);
}

/// Sparse starfield — even sparser than midnight so neon pops.
fn neonStarfield(uv: vec2<f32>) -> vec3<f32> {
  let grid = floor(uv * vec2<f32>(100.0, 75.0));
  let h = fract(sin(dot(grid, vec2<f32>(127.1, 311.7))) * 43758.5453);
  let h2 = fract(sin(dot(grid + 1.0, vec2<f32>(269.5, 183.3))) * 43758.5453);

  if (h > 0.985) {
    let brightness = h2 * 0.012;
    return vec3<f32>(0.85, 0.90, 1.0) * brightness;
  }
  return vec3<f32>(0.0);
}

/// Neon grid lines — faint cyan on vertical edges, magenta on horizontal.
fn neonGrid(uv: vec2<f32>, p: vec2<f32>, isPlaying: bool) -> vec3<f32> {
  let edgeX = abs(p.x - 0.0);  // vertical cell edge
  let edgeY = abs(p.y - 0.0);  // horizontal cell edge

  let vertLine = exp(-edgeX * edgeX * 180.0) * 0.035;
  let horzLine = exp(-edgeY * edgeY * 180.0) * 0.025;

  var col = vec3<f32>(0.0);
  if (isPlaying) {
    col += NEON_CYAN    * vertLine;
    col += NEON_MAGENTA * horzLine;
  } else {
    col += CYAN_DIM    * vertLine;
    col += MAGENTA_DIM * horzLine;
  }
  return col;
}

/// Neon rim glow on housing border.
fn neonRim(dHousing: f32, aa: f32, isPlaying: bool) -> vec3<f32> {
  let rim = smoothstep(aa * 3.0, 0.0, dHousing) * smoothstep(0.0, aa * 2.0, dHousing + aa * 2.5);
  if (!isPlaying) { return CYAN_DIM * rim * 0.3; }
  return mix(NEON_CYAN, NEON_MAGENTA, 0.5) * rim * 0.45;
}

/// Neon scanline overlay — subtle horizontal bands.
fn neonScanlines(uv: vec2<f32>, time: f32) -> vec3<f32> {
  let band = sin(uv.y * 120.0 + time * 0.5) * 0.5 + 0.5;
  let intensity = band * 0.008;
  return NEON_CYAN * intensity;
}

/// Ghost echo with neon tint based on channel parity.
fn neonGhostEcho(p: vec2<f32>, noteAge: f32, bloom: f32, channel: u32) -> vec3<f32> {
  if (noteAge > 4.0 || noteAge < 0.0) { return vec3<f32>(0.0); }
  let ageFade = exp(-noteAge * 1.2);
  let spatialFade = exp(-length(p) * 2.5);
  let echo = ageFade * spatialFade * bloom * 0.4;
  let tint = select(NEON_CYAN * 0.15, NEON_MAGENTA * 0.15, (channel % 2u) == 0u);
  return tint * echo;
}

/// Ultra-subtle grain.
fn neonGrain(uv: vec2<f32>, time: f32) -> vec3<f32> {
  let t = time * 0.04;
  let h = fract(sin(dot(uv * 2.3 + t, vec2<f32>(127.1, 311.7))) * 43758.5453);
  return vec3<f32>((h - 0.5) * 0.004);
}

// ═══════════════════════════════════════════════════════════
// FRAGMENT SHADER
// ═══════════════════════════════════════════════════════════

@fragment
fn fs(in: VertexOut) -> @location(0) vec4<f32> {
  let uv = in.uv;
  let p = uv - 0.5;
  let aa = fwidth(p.y) * 0.5;
  let bloom = uniforms.bloomIntensity;
  let time = uniforms.timeSec;
  let isPlaying = (uniforms.isPlaying == 1u);
  let dimFactor = uniforms.dimFactor;

  // ═══════════════════════════════════════════════════════════
  // CHANNEL 0 — DUAL-COLOUR PLAYHEAD INDICATOR
  // ═══════════════════════════════════════════════════════════
  if (in.channel == 0u) {
    let onPlayhead = (in.row == u32(uniforms.playheadRow));
    let breathe = neonBreathe(time);

    var col = NEON_BLACK;
    var alpha = 0.0;

    if (onPlayhead) {
      let core = exp(-length(p) * 9.0);
      col = NEON_CYAN * core * breathe.x + NEON_MAGENTA * core * breathe.y * 0.5;
      alpha = core * 0.9;

      let ring = exp(-length(p) * 3.8) * 0.45;
      col += mix(NEON_CYAN, NEON_MAGENTA, sin(time * 2.0) * 0.5 + 0.5) * ring * bloom;
      alpha = max(alpha, ring * 0.35);
    }

    return vec4<f32>(col, clamp(alpha, 0.0, 1.0));
  }

  // ═══════════════════════════════════════════════════════════
  // MUSIC CHANNELS (1–32)
  // ═══════════════════════════════════════════════════════════

  let dHousing = sdRoundedBox(p, fs.housingSize * 0.5, 0.06);
  let housingMask = 1.0 - smoothstep(0.0, aa * 1.5, dHousing);

  var finalColor = NEON_BLACK;

  // Starfield dust
  finalColor += neonStarfield(in.uv);

  // Neon grid lines (subtle, behind everything)
  finalColor += neonGrid(in.uv, p, isPlaying);

  // Neon rim on housing
  finalColor += neonRim(dHousing, aa, isPlaying);

  let btnScale = 1.05;
  let btnUV = (uv - 0.5) * btnScale + 0.5;
  var inButton = 0.0;
  if (btnUV.x > 0.0 && btnUV.x < 1.0 && btnUV.y > 0.0 && btnUV.y < 1.0) {
    inButton = 1.0;
  }

  if (in.channel >= uniforms.numChannels) {
    return vec4<f32>(1.0, 0.0, 0.0, 1.0);
  }

  if (inButton > 0.5) {
    let noteChar = (in.packedA >> 24) & 255u;
    let inst = in.packedA & 255u;
    let volCmd = (in.packedA >> 8) & 255u;
    let effCode = (in.packedB >> 8) & 255u;
    let effParam = in.packedB & 255u;

    let hasNote = (noteChar >= 65u && noteChar <= 122u);
    let hasExpression = (volCmd > 0u) || (effCode > 0u);
    let ch = channels[in.channel];
    let isMuted = (ch.isMuted == 1u);

    let maxRows = f32(uniforms.numRows);
    let playheadStep = uniforms.playheadRow - floor(uniforms.playheadRow / maxRows) * maxRows;
    let rowDistRaw = abs(f32(in.row % uniforms.numRows) - playheadStep);
    let rowDist = min(rowDistRaw, maxRows - rowDistRaw);
    let onPlayhead = rowDist < 1.5;

    // ── NEON GHOST ECHO ──
    if (!isMuted && ch.noteAge < 4.0 && ch.noteAge >= 0.0) {
      finalColor += neonGhostEcho(p, ch.noteAge, bloom, in.channel);
    }

    // ── MAIN NOTE LIGHT ──
    var noteColor = vec3<f32>(0.0);
    var lightAmount = 0.0;

    if (hasNote && !isMuted) {
      let pitchHue = pitchClassFromPacked(in.packedA);
      let baseColor = neonPalette(pitchHue);
      let saturated = pow(baseColor, vec3<f32>(0.70));
      let instBand = inst & 15u;
      let instBright = 0.9 + (select(0.0, f32(instBand) / 15.0, instBand > 0u)) * 0.2;
      noteColor = saturated * instBright;

      // Boost cyan/magenta notes for neon consistency
      let dominant = max(noteColor.r, max(noteColor.g, noteColor.b));
      if (noteColor.g > 0.5 && noteColor.b > 0.5 && noteColor.r < 0.3) {
        noteColor = mix(noteColor, NEON_CYAN, 0.25);
      } else if (noteColor.r > 0.5 && noteColor.b > 0.3 && noteColor.g < 0.4) {
        noteColor = mix(noteColor, NEON_MAGENTA, 0.25);
      }

      let linger = exp(-ch.noteAge * 1.5);
      let strike = select(0.0, 4.0, onPlayhead);
      let flash = f32(ch.trigger) * 1.5;

      let totalSteps = f32(uniforms.numRows);
      let d = fract((f32(in.row) + uniforms.tickOffset - uniforms.playheadRow) / totalSteps) * totalSteps;
      let coreDist = min(d, totalSteps - d);
      let energy = 0.02 / (coreDist + 0.001);
      let trail = exp(-10.0 * max(0.0, -d + totalSteps * 0.5));
      let activeVal = clamp(pow(energy, 1.5) + trail, 0.0, 1.0);

      lightAmount = (activeVal * 0.8 + flash + strike + (linger * 2.0)) * clamp(ch.volume, 0.0, 1.2);
    }

    if (lightAmount > 0.01) {
      let mainUV = btnUV - vec2<f32>(0.5, 0.5);
      let mainSize = vec2<f32>(0.55, 0.45);

      let displayColor = noteColor * max(lightAmount, 0.1) * (1.0 + bloom * 10.0);
      let isLit = (lightAmount > 0.05);
      let mainPad = drawChromeIndicator(mainUV, mainSize, displayColor, isLit, aa, dimFactor);
      finalColor = mix(finalColor, mainPad.rgb, mainPad.a);

      // Neon-tinted bloom bleed — colour depends on channel parity
      let bleedRadius = length(mainUV) / 0.7;
      let bleed = exp(-bleedRadius * bleedRadius * 4.0) * lightAmount * bloom * 0.6;
      let bleedTint = select(NEON_CYAN * 0.4, NEON_MAGENTA * 0.4, (in.channel % 2u) == 0u);
      finalColor += mix(noteColor, bleedTint, 0.35) * bleed;
    }

    // ── NEON EXPRESSION LIGHT ──
    // Cyan for even channels, magenta for odd — only when active
    if (hasExpression && !isMuted && (onPlayhead || ch.trigger > 0u)) {
      let exprUV = btnUV - vec2<f32>(0.5, 0.82);
      let exprSz = vec2<f32>(0.25, 0.12);
      let exprCol = select(NEON_CYAN, NEON_MAGENTA, (in.channel % 2u) == 0u) * (0.6 + bloom);
      let exprLed = drawChromeIndicator(exprUV, exprSz, exprCol, true, aa, dimFactor);
      finalColor = mix(finalColor, exprLed.rgb, exprLed.a * 0.7);
    }

    // ── PLAYHEAD ROW HIGHLIGHT ──
    if (onPlayhead && !isMuted) {
      let lineIntensity = (1.0 - smoothstep(0.0, 0.25, rowDist)) * 0.15;
      let lineCol = mix(NEON_CYAN, NEON_MAGENTA, sin(f32(in.channel) * 0.5) * 0.5 + 0.5);
      finalColor += lineCol * lineIntensity * bloom;
    }
  }

  // ═══════════════════════════════════════════════════════════
  // POST-PROCESSING
  // ═══════════════════════════════════════════════════════════

  if (housingMask < 0.5) { return vec4<f32>(fs.borderColor, 0.0); }

  // Kick reactive — neon amber flash
  let kickPulse = uniforms.kickTrigger * exp(-length(p) * 3.0) * 0.25;
  finalColor += NEON_AMBER * kickPulse * uniforms.bloomIntensity;

  // Neon scanlines
  finalColor += neonScanlines(in.uv, time);

  // Grain + dither
  finalColor += neonGrain(in.uv, time);
  finalColor += ditherNoise(in.uv, time);

  return vec4<f32>(finalColor, 1.0);
}
