// ============================================================
// patternv0.39.wgsl
//
// GENERATED by scripts/build-shaders.mjs — DO NOT EDIT DIRECTLY.
// Source: shaders/src/patternv0.39.wgsl
//
// To regenerate:
//   npm run build:shaders
// ============================================================

// ============================================================
// patternv0.39.wgsl — Source file
// Classic circular pattern with ASCII-packed note parsing
//
// Assembled via build-shaders.mjs from:
//   #include "common.wgsl"
//   #include "sdf_primitives.wgsl"
//   #include "color_palettes.wgsl"
//   #include "note_parsing.wgsl"
//   #include "bloom_effects.wgsl"
// ============================================================

// >>> begin include "common.wgsl"  (shaders/include/common.wgsl)
// #pragma once  (shaders/include/common.wgsl)
// ============================================================
// common.wgsl — Shared uniforms, structs, bindings, and
//               circular vertex shader for classic pattern shaders.
//
// Include this FIRST. It defines Uniforms, bindings, VertexOut,
// and the circular-layout vertex stage. Pure math utilities
// (SDFs, palettes) have been moved to dedicated includes.
// ============================================================

// ── Math Constants ──
const PI: f32 = 3.14159265;
const TAU: f32 = 6.2831853;
const PI_HALF: f32 = 1.570796;

// ── Note Range Constants ──
const NOTE_MIN: u32 = 1u;
const NOTE_MAX: u32 = 119u;
const NOTE_OFF_MIN: u32 = 120u;

// ── Shared Color Constants ──
/// Near-black used for dead / empty / expression-only cells.
const DEAD_COLOR: vec3<f32> = vec3<f32>(0.051, 0.051, 0.051);

/// Dark glass background used inside lens caps and housing.
const GLASS_BG: vec3<f32> = vec3<f32>(0.04, 0.04, 0.05);

/// Unlit diode housing color.
const DIODE_HOUSING: vec3<f32> = vec3<f32>(0.06, 0.06, 0.08);

// ── Uniforms ──
struct Uniforms {
  numRows: u32,
  numChannels: u32,
  playheadRow: f32,
  isPlaying: u32,
  cellW: f32,
  cellH: f32,
  canvasW: f32,
  canvasH: f32,
  tickOffset: f32,
  bpm: f32,
  timeSec: f32,
  beatPhase: f32,
  groove: f32,
  kickTrigger: f32,
  activeChannels: u32,
  isModuleLoaded: u32,
  bloomIntensity: f32,
  bloomThreshold: f32,
  invertChannels: u32,
  dimFactor: f32,
  _r0: f32,
  _r1: f32,
  _r2: f32,
  _r3: f32,
  colorPalette: u32,
};

// ── Storage & Uniform Bindings ──
@group(0) @binding(0) var<storage, read> cells: array<u32>;
@group(0) @binding(1) var<uniform> uniforms: Uniforms;
@group(0) @binding(2) var<storage, read> rowFlags: array<u32>;

struct ChannelState {
  volume: f32,
  pan: f32,
  freq: f32,
  trigger: u32,
  noteAge: f32,
  activeEffect: u32,
  effectValue: f32,
  isMuted: u32
};
@group(0) @binding(3) var<storage, read> channels: array<ChannelState>;

@group(0) @binding(4) var buttonsSampler: sampler;
@group(0) @binding(5) var buttonsTexture: texture_2d<f32>;

// ── Vertex I/O ──
struct VertexOut {
  @builtin(position) position: vec4<f32>,
  @location(0) @interpolate(flat) row: u32,
  @location(1) @interpolate(flat) channel: u32,
  @location(2) @interpolate(linear) uv: vec2<f32>,
  @location(3) @interpolate(flat) packedA: u32,
  @location(4) @interpolate(flat) packedB: u32,
};

// ── Vertex Shader ──
/// Circular ring layout: each cell becomes a rotated quad positioned
/// radially according to its channel (ring index) and row (angle).
/// Channel 0 is reserved for the indicator ring when padTopChannel=true.
@vertex
fn vs(@builtin(vertex_index) vertexIndex: u32, @builtin(instance_index) instanceIndex: u32) -> VertexOut {
  var quad = array<vec2<f32>, 6>(
    vec2<f32>(0.0, 0.0), vec2<f32>(1.0, 0.0), vec2<f32>(0.0, 1.0),
    vec2<f32>(0.0, 1.0), vec2<f32>(1.0, 0.0), vec2<f32>(1.0, 1.0)
  );

  let numChannels = uniforms.numChannels;
  let row = instanceIndex / numChannels;
  let channel = instanceIndex % numChannels;

  let invertedChannel = numChannels - 1u - channel;
  let ringIndex = select(invertedChannel, channel, (uniforms.invertChannels == 1u));

  let center = vec2<f32>(uniforms.canvasW * 0.5, uniforms.canvasH * 0.5);
  let minDim = min(uniforms.canvasW, uniforms.canvasH);

  let maxRadius = minDim * 0.45;
  let minRadius = minDim * 0.15;
  let ringDepth = (maxRadius - minRadius) / f32(numChannels);

  let radius = minRadius + f32(ringIndex) * ringDepth;

  let totalSteps = f32(uniforms.numRows);
  let anglePerStep = TAU / totalSteps;
  let theta = -PI_HALF + f32(row % uniforms.numRows) * anglePerStep;

  let circumference = 2.0 * PI * radius;
  let arcLength = circumference / totalSteps;

  let btnW = arcLength * 0.95;
  let btnH = ringDepth * 0.95;

  let lp = quad[vertexIndex];
  let localPos = (lp - 0.5) * vec2<f32>(btnW, btnH);

  let rotAng = theta + PI_HALF;
  let cA = cos(rotAng);
  let sA = sin(rotAng);

  let rotX = localPos.x * cA - localPos.y * sA;
  let rotY = localPos.x * sA + localPos.y * cA;

  let worldX = center.x + cos(theta) * radius + rotX;
  let worldY = center.y + sin(theta) * radius + rotY;

  let clipX = (worldX / uniforms.canvasW) * 2.0 - 1.0;
  let clipY = 1.0 - (worldY / uniforms.canvasH) * 2.0;

  // High-precision packing: two u32s per cell (PackedA + PackedB)
  let idx = instanceIndex * 2u;
  let a = cells[idx];
  let b = cells[idx + 1u];

  var out: VertexOut;
  out.position = vec4<f32>(clipX, clipY, 0.0, 1.0);
  out.row = row;
  out.channel = channel;
  out.uv = lp;
  out.packedA = a;
  out.packedB = b;
  return out;
}

// ── Include helpers (move to dedicated includes) ──
//   sdf_primitives.wgsl  — sdRoundedBox, sdCircle, sdEllipse
//   color_palettes.wgsl  — selectPalette, neonPalette, pitchClassFromIndex

// <<< end include "common.wgsl"  (shaders/include/common.wgsl)
// >>> begin include "sdf_primitives.wgsl"  (shaders/include/sdf_primitives.wgsl)
// #pragma once  (shaders/include/sdf_primitives.wgsl)
// ============================================================
// sdf_primitives.wgsl — Signed-distance field primitives.
//
// Include AFTER common.wgsl or bloom/core.wgsl.
// No bindings or uniforms are declared here.
// ============================================================

/// Signed distance to a rounded rectangle.
fn sdRoundedBox(p: vec2<f32>, b: vec2<f32>, r: f32) -> f32 {
  let q = abs(p) - b + r;
  return length(max(q, vec2<f32>(0.0))) + min(max(q.x, q.y), 0.0) - r;
}

/// Signed distance to a circle.
fn sdCircle(p: vec2<f32>, r: f32) -> f32 {
  return length(p) - r;
}

/// Signed distance to an ellipse.
fn sdEllipse(p: vec2<f32>, ab: vec2<f32>) -> f32 {
  let k = length(p / ab);
  return (k - 1.0) * min(ab.x, ab.y);
}

/// Signed distance to an axis-aligned box.
fn sdBox(p: vec2<f32>, b: vec2<f32>) -> f32 {
  let d = abs(p) - b;
  return length(max(d, vec2<f32>(0.0))) + min(max(d.x, d.y), 0.0);
}

/// Signed distance to an equilateral triangle (pointing up).
fn sdTriangle(p: vec2<f32>, r: f32) -> f32 {
  let k = sqrt(3.0);
  var p2 = p;
  p2.x = abs(p2.x) - r;
  p2.y = p2.y + r / k;
  if (p2.x + k * p2.y > 0.0) { p2 = vec2<f32>(p2.x - k * p2.y, -k * p2.x - p2.y) / 2.0; }
  p2.x = p2.x - clamp(p2.x, -2.0 * r, 0.0);
  return -length(p2) * sign(p2.y);
}

// <<< end include "sdf_primitives.wgsl"  (shaders/include/sdf_primitives.wgsl)
// >>> begin include "color_palettes.wgsl"  (shaders/include/color_palettes.wgsl)
// #pragma once  (shaders/include/color_palettes.wgsl)
// ============================================================
// color_palettes.wgsl — Color palette and pitch-class helpers.
//
// Include AFTER common.wgsl or bloom/core.wgsl (needs TAU).
// ============================================================

/// Select a color palette by ID (0–4). All palettes use the same
/// cosine gradient basis with different phase offsets.
fn selectPalette(id: u32, t: f32) -> vec3<f32> {
  let a = vec3<f32>(0.5, 0.5, 0.5);
  let b = vec3<f32>(0.5, 0.5, 0.5);
  let c = vec3<f32>(1.0, 1.0, 1.0);
  if (id == 1u) {
    // Warm: reds, oranges, yellows
    return a + b * cos(TAU * (c * t + vec3<f32>(0.0, 0.1, 0.2)));
  } else if (id == 2u) {
    // Cool: blues, cyans, purples
    return a + b * cos(TAU * (c * t + vec3<f32>(0.5, 0.7, 0.9)));
  } else if (id == 3u) {
    // Neon: pink, cyan, green
    return a + b * cos(TAU * (c * t + vec3<f32>(0.0, 0.5, 1.0)));
  } else if (id == 4u) {
    // Acid: green, yellow, chartreuse
    return a + b * cos(TAU * (c * t + vec3<f32>(0.3, 0.0, 0.7)));
  }
  // Default palette 0: Rainbow
  return a + b * cos(TAU * (c * t + vec3<f32>(0.0, 0.33, 0.67)));
}

/// Classic rainbow cosine gradient. Equivalent to selectPalette(0u, t).
fn neonPalette(t: f32) -> vec3<f32> {
  return selectPalette(0u, t);
}

/// Map a tracker note index (1–119) to a pitch-class hue [0,1).
fn pitchClassFromIndex(note: u32) -> f32 {
  if (note == 0u || note >= NOTE_OFF_MIN) { return 0.0; }
  let semi = (note - 1u) % 12u;
  return f32(semi) / 12.0;
}

// <<< end include "color_palettes.wgsl"  (shaders/include/color_palettes.wgsl)
// >>> begin include "note_parsing.wgsl"  (shaders/include/note_parsing.wgsl)
// #pragma once  (shaders/include/note_parsing.wgsl)
// ============================================================
// note_parsing.wgsl — Note and effect parsing helpers.
//
// Include AFTER common.wgsl or bloom/core.wgsl.
// ============================================================

/// Convert an ASCII character to uppercase (A–Z / a–z only).
fn toUpperAscii(code: u32) -> u32 {
  if (code >= 97u && code <= 122u) {
    return code - 32u;
  }
  return code;
}

/// Map an ASCII-packed note representation to a pitch-class hue [0,1).
/// Used by high-precision shaders where the note is stored as ASCII
/// characters in the upper bytes of packedA.
fn pitchClassFromPacked(packed: u32) -> f32 {
  let c0 = toUpperAscii((packed >> 24) & 255u);
  var semitone: i32 = 0;
  var valid = true;
  switch (c0) {
    case 65u: { semitone = 9; }   // A
    case 66u: { semitone = 11; }  // B
    case 67u: { semitone = 0; }   // C
    case 68u: { semitone = 2; }   // D
    case 69u: { semitone = 4; }   // E
    case 70u: { semitone = 5; }   // F
    case 71u: { semitone = 7; }   // G
    default: { valid = false; }
  }
  if (!valid) { return 0.0; }
  let c1 = toUpperAscii((packed >> 16) & 255u);
  if ((c1 == 35u) || (c1 == 43u)) {        // # or +
    semitone = (semitone + 1) % 12;
  } else if (c1 == 66u) {                  // b (flat)
    semitone = (semitone + 11) % 12;
  }
  return f32(semitone) / 12.0;
}

/// Convert an effect command code (ASCII) to a tinted color.
fn effectColorFromCode(code: u32, fallback: vec3<f32>) -> vec3<f32> {
  let c = toUpperAscii(code & 255u);
  switch c {
    case 49u: { return mix(fallback, vec3<f32>(0.2, 0.85, 0.4), 0.75); } // 1xx Porta Up — Green
    case 50u: { return mix(fallback, vec3<f32>(0.85, 0.3, 0.3), 0.75); } // 2xx Porta Down — Red
    case 52u: { return mix(fallback, vec3<f32>(0.4, 0.7, 1.0), 0.6); }  // 4xx Vibrato — Blue
    case 55u: { return mix(fallback, vec3<f32>(0.9, 0.6, 0.2), 0.6); }  // 7xx Tremolo — Orange
    case 65u: { return mix(fallback, vec3<f32>(0.95, 0.9, 0.25), 0.7); } // Axx VolSlide — Yellow
    default:  { return fallback; }
  }
}

// <<< end include "note_parsing.wgsl"  (shaders/include/note_parsing.wgsl)
// >>> begin include "bloom_effects.wgsl"  (shaders/include/bloom_effects.wgsl)
// #pragma once  (shaders/include/bloom_effects.wgsl)
// ============================================================
// bloom_effects.wgsl — Bloom intensity curves, glow kernels,
// kick-reactive flash, and film-grain dither.
//
// Include AFTER common.wgsl or bloom/core.wgsl.
// ============================================================

/// High-intensity boost: base + bloom * 2.0
fn bloomBoost(base: f32, bloom: f32) -> f32 {
  return base + bloom * 2.0;
}

/// Medium boost: base + bloom * 1.0
fn bloomBoostMedium(base: f32, bloom: f32) -> f32 {
  return base + bloom * 1.0;
}

/// Soft ambient boost: base + bloom * 0.2
fn bloomSoft(base: f32, bloom: f32) -> f32 {
  return base + bloom * 0.2;
}

/// Exponential radial glow kernel.
fn pointGlow(p: vec2<f32>, color: vec3<f32>, intensity: f32, falloff: f32) -> vec3<f32> {
  return color * intensity * exp(-length(p) * falloff);
}

/// Kick-reactive magenta bloom flash.
fn kickReactiveGlow(p: vec2<f32>, kick: f32, bloom: f32) -> vec3<f32> {
  let kickPulse = kick * exp(-length(p) * 3.0) * 0.3;
  return vec3<f32>(0.9, 0.2, 0.4) * kickPulse * bloom;
}

/// Film-grain dither to reduce banding in dark regions.
fn ditherNoise(uv: vec2<f32>, time: f32) -> f32 {
  let noise = fract(sin(dot(uv * time, vec2<f32>(12.9898, 78.233))) * 43758.5453);
  return (noise - 0.5) * 0.01;
}

// <<< end include "bloom_effects.wgsl"  (shaders/include/bloom_effects.wgsl)

@fragment
fn fs(in: VertexOut) -> @location(0) vec4<f32> {
  let uv = in.uv;
  let p = uv - 0.5;
  let aa = fwidth(p.y) * 0.33;

  if (in.channel >= uniforms.numChannels) { return vec4<f32>(1.0, 0.0, 0.0, 1.0); }
  let bloom = uniforms.bloomIntensity;
  let kick = uniforms.kickTrigger;
  let beat = uniforms.beatPhase;

  // Smooth playhead position
  let maxRows = f32(uniforms.numRows);
  let playheadStep = uniforms.playheadRow - floor(uniforms.playheadRow / maxRows) * maxRows;
  let rowDistRaw = abs(f32(in.row % uniforms.numRows) - playheadStep);
  let rowDist = min(rowDistRaw, maxRows - rowDistRaw);
  let playheadActivation = 1.0 - smoothstep(0.0, 1.5, rowDist);

  // ── INDICATOR RING ──
  if (in.channel == 0u) {
    let onPlayhead = (f32(in.row) == uniforms.playheadRow);
    let indSize = vec2<f32>(0.3, 0.3);
    let indColor = mix(vec3<f32>(0.15), vec3<f32>(1.0, 0.55, 0.1) * 1.3, playheadActivation);
    let dBox = sdRoundedBox(p, indSize * 0.5, 0.08);
    let edgeAlpha = smoothstep(0.0, aa * 2.0, -dBox);
    var col = mix(vec3<f32>(0.04), indColor, playheadActivation * 0.8);
    var alpha = edgeAlpha;
    if (playheadActivation > 0.0) {
      let beatPulse = 1.0 + kick * 0.6 + (0.5 + 0.5 * sin(beat * TAU)) * 0.2;
      let glow = vec3<f32>(1.0, 0.55, 0.1) * (bloom * 5.0) * exp(-length(p) * 3.5) * playheadActivation * beatPulse;
      col += glow;
      alpha = max(alpha, smoothstep(0.0, 0.25, length(glow)));
    }
    return vec4<f32>(col, clamp(alpha, 0.0, 1.0));
  }

  let dHousing = sdRoundedBox(p, vec2<f32>(0.46), 0.06);
  let housingMask = 1.0 - smoothstep(0.0, aa * 1.5, dHousing);

  var finalColor = vec3<f32>(0.04, 0.04, 0.05);

  let btnScale = 1.05;
  let btnUV = (uv - 0.5) * btnScale + 0.5;
  var inButton = 0.0;
  if (btnUV.x > 0.0 && btnUV.x < 1.0 && btnUV.y > 0.0 && btnUV.y < 1.0) {
    inButton = 1.0;
  }

  if (inButton > 0.5) {
    let noteChar = (in.packedA >> 24) & 255u;
    let inst = (in.packedA >> 16) & 255u;
    let volCmd = (in.packedA >> 8) & 255u;
    let volVal = in.packedA & 255u;

    let effCmd = (in.packedB >> 8) & 255u;
    let effVal = in.packedB & 255u;

    let hasNote = (noteChar >= 65u && noteChar <= 71u);
    let hasExpression = (volCmd > 0u) || (effCmd > 0u);

    let ch = channels[in.channel];
    let isMuted = (ch.isMuted == 1u);

    var noteCol = vec3<f32>(0.15);
    var noteGlow = 0.0;

    if (hasNote) {
      let pitchHue = pitchClassFromPacked(in.packedA);
      noteCol = selectPalette(uniforms.colorPalette, pitchHue);
      let instBand = inst & 15u;
      let instBright = 0.85 + (select(0.0, f32(instBand) / 15.0, instBand > 0u)) * 0.15;
      noteCol *= instBright;

      let decay = exp(-ch.noteAge * 2.5);
      let flash = f32(ch.trigger);
      noteGlow = (decay + flash) * (1.0 + bloom * 3.0);
      if (isMuted) { noteGlow *= 0.25; }
    }

    // Main cap
    let mainUV = btnUV - vec2<f32>(0.5, 0.5);
    let mainSz = vec2<f32>(0.55, 0.45);
    let dBox = sdRoundedBox(mainUV, mainSz * 0.5, 0.08);
    let edgeAlpha = smoothstep(0.0, aa * 2.0, -dBox);

    let n = normalize(vec3<f32>(mainUV.x * 2.0 / mainSz.x, mainUV.y * 2.0 / mainSz.y, 0.35));
    let light = normalize(vec3<f32>(0.5, -0.8, 1.0));
    let diff = max(0.0, dot(n, light));
    let fresnel = pow(1.0 - max(0.0, dot(n, vec3<f32>(0.0, 0.0, 1.0))), 2.5);

    var capColor = mix(vec3<f32>(0.05, 0.05, 0.06), noteCol, 0.8);
    capColor *= (0.55 + 0.45 * diff);
    capColor += fresnel * 0.15;
    capColor += noteGlow * noteCol * 0.5;

    finalColor = mix(finalColor, capColor, edgeAlpha);

    // Playhead pulse
    if (playheadActivation > 0.5 && noteGlow > 0.0) {
      finalColor += noteCol * playheadActivation * 0.12;
    }

    // Expression indicator
    if (hasExpression && !isMuted) {
      let exprCenter = vec2<f32>(0.0, -0.32);
      let exprDist = length(mainUV - exprCenter);
      let exprMask = 1.0 - smoothstep(0.04, 0.07, exprDist);
      let exprCol = vec3<f32>(0.0, 0.75, 1.0) * (0.8 + bloom * 0.5);
      finalColor = mix(finalColor, exprCol, exprMask * 0.85);
    }
  }

  finalColor += kickReactiveGlow(p, kick, bloom);
  finalColor += ditherNoise(in.uv, uniforms.timeSec);

  if (housingMask < 0.5) { return vec4<f32>(vec3<f32>(0.0), 0.0); }
  return vec4<f32>(finalColor, 1.0);
}
