/**
 * Real-WASM libopenmpt assets shared by EVERY JS-engine consumer:
 *   - AudioWorklet (main thread fetches both files → initLib {scriptText, wasmBytes})
 *   - main thread  (<script src> injected into index.html by vite-plugins/libopenmptHtml.ts)
 *   - parser worker (workers/openmpt-parser.worker.ts, locateFile → the same .wasm)
 *
 * Built by scripts/build-js-libopenmpt.sh into public/worklets/ and described by the generated
 * manifest below (SRI hashes + a content-hash cache key). Nothing here replaces
 * globalThis.WebAssembly, so the native engine can instantiate without any snapshot.
 */
import manifest from '../audio-worklet/js/libopenmpt-worklet.generated.json';

/** libopenmpt release the artifact was built from (vendor/libopenmpt-* in build-js-libopenmpt.sh). */
export const LIBOPENMPT_VERSION = manifest.libopenmpt;

/** Directory under the site base URL that holds the glue + wasm (e.g. /xm-player/worklets/). */
export const LIBOPENMPT_DIR = 'worklets';

export const LIBOPENMPT_GLUE_FILE = manifest.glue.file;
export const LIBOPENMPT_WASM_FILE = manifest.wasm.file;

/** SRI for the self-hosted glue script tag (regenerated by every build-js-libopenmpt run). */
export const LIBOPENMPT_JS_INTEGRITY = manifest.glue.integrity;
export const LIBOPENMPT_WASM_INTEGRITY = manifest.wasm.integrity;

/**
 * Content hash of glue+wasm. Appended as ?v= to every request so an HTTP cache or the service
 * worker can never pair a new glue with an old .wasm (their import tables are minified per build).
 */
export const LIBOPENMPT_ASSET_VERSION = manifest.version;

function normalizeTrailingSlash(url: string): string {
  return url.endsWith('/') ? url : `${url}/`;
}

/** Base URL for the libopenmpt glue + wasm (trailing slash). */
export function getLibOpenMPTBaseUrl(): string {
  const base = import.meta.env.BASE_URL || '/';
  return normalizeTrailingSlash(`${base}${LIBOPENMPT_DIR}`);
}

function versioned(url: string): string {
  return `${url}?v=${LIBOPENMPT_ASSET_VERSION}`;
}

export function getLibOpenMPTJsUrl(): string {
  return versioned(`${getLibOpenMPTBaseUrl()}${LIBOPENMPT_GLUE_FILE}`);
}

export function getLibOpenMPTWasmUrl(): string {
  return versioned(`${getLibOpenMPTBaseUrl()}${LIBOPENMPT_WASM_FILE}`);
}

/**
 * Emscripten locateFile hook for contexts where document.currentScript is unavailable
 * (parser worker evaluates the glue with new Function). Only the wasm is ever requested.
 */
export function createLibOpenMPTLocateFile(): (path: string) => string {
  // BASE_URL is site-relative (e.g. /xm-player/): `new URL(x, '/relative/')` throws, so
  // anchor on the worker's own location first.
  const origin = globalThis.location?.href ?? 'http://localhost/';
  const base = new URL(getLibOpenMPTBaseUrl(), origin).href;
  return (path: string) => versioned(new URL(path, base).href);
}
