#!/usr/bin/env node
/**
 * WGSL Include Build Script
 *
 * Processes `.wgsl` source files in `shaders/src/` that use `#include "path"`
 * directives and emits fully-assembled shaders to `public/shaders/`.
 *
 * Standalone `.wgsl` files in `shaders/` (not in src/, include/, or archive/)
 * are also copied to `public/shaders/` so legacy shaders continue to work.
 *
 * Usage:
 *   node scripts/build-shaders.mjs
 *
 * Include resolution:
 *   1. Relative to `shaders/include/`      (primary search path)
 *   2. Relative to the including file      (fallback)
 *
 * Directives:
 *   #include "file.wgsl"   — inline the named file
 *   #pragma once           — skipped on subsequent includes (guard)
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const SRC_DIR = path.join(ROOT, 'shaders', 'src');
const INCLUDE_DIR = path.join(ROOT, 'shaders', 'include');
const SHADERS_DIR = path.join(ROOT, 'shaders');
const OUT_DIR = path.join(ROOT, 'public', 'shaders');

const INCLUDE_RE = /^\s*#include\s+"([^"]+)"\s*$/;
const PRAGMA_ONCE_RE = /^\s*#pragma\s+once\s*$/;

function resolveInclude(includePath, fromFile) {
  // 1. Try relative to shaders/include/
  const fromInclude = path.join(INCLUDE_DIR, includePath);
  if (fs.existsSync(fromInclude)) return fromInclude;

  // 2. Try relative to the including file's directory
  const fromDir = path.join(path.dirname(fromFile), includePath);
  if (fs.existsSync(fromDir)) return fromDir;

  throw new Error(
    `Include not found: "${includePath}"\n` +
    `  looked in: ${fromInclude}\n` +
    `  looked in: ${fromDir}\n` +
    `  required by: ${fromFile}`
  );
}

function processFile(filePath, includedSet = new Set(), depth = 0) {
  if (depth > 32) {
    throw new Error(`Include depth exceeded (circular include?) in ${filePath}`);
  }

  const absPath = path.resolve(filePath);
  if (includedSet.has(absPath)) {
    // Already included — emit nothing (pragma-once behavior by default)
    return '';
  }

  const content = fs.readFileSync(absPath, 'utf-8');
  const lines = content.split('\n');
  const outLines = [];
  let hasPragmaOnce = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    if (PRAGMA_ONCE_RE.test(line)) {
      hasPragmaOnce = true;
      outLines.push(`// #pragma once  (${path.relative(ROOT, absPath)})`);
      continue;
    }

    const includeMatch = line.match(INCLUDE_RE);
    if (includeMatch) {
      const includePath = includeMatch[1];
      const resolved = resolveInclude(includePath, absPath);
      const relResolved = path.relative(ROOT, resolved);
      outLines.push(`// >>> begin include "${includePath}"  (${relResolved})`);
      outLines.push(processFile(resolved, includedSet, depth + 1));
      outLines.push(`// <<< end include "${includePath}"  (${relResolved})`);
      continue;
    }

    outLines.push(line);
  }

  if (hasPragmaOnce) {
    includedSet.add(absPath);
  }

  return outLines.join('\n');
}

function buildSourceFile(srcPath) {
  const basename = path.basename(srcPath);
  const outPath = path.join(OUT_DIR, basename);

  console.log(`  → ${basename}`);
  const assembled = processFile(srcPath);

  const header =
    `// ============================================================\n` +
    `// ${basename}\n` +
    `//\n` +
    `// GENERATED by scripts/build-shaders.mjs — DO NOT EDIT DIRECTLY.\n` +
    `// Source: shaders/src/${basename}\n` +
    `//\n` +
    `// To regenerate:\n` +
    `//   npm run build:shaders\n` +
    `// ============================================================\n\n`;

  fs.writeFileSync(outPath, header + assembled, 'utf-8');
}

function copyStandaloneLegacy() {
  const copied = [];
  const entries = fs.readdirSync(SHADERS_DIR, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.wgsl')) continue;

    const src = path.join(SHADERS_DIR, entry.name);
    const dst = path.join(OUT_DIR, entry.name);

    // Don't overwrite files we just generated from shaders/src/
    if (fs.existsSync(dst)) continue;

    fs.copyFileSync(src, dst);
    console.log(`  → ${entry.name}  (legacy copy)`);
    copied.push(entry.name);
  }
  return copied;
}

function clearStaleOutputs() {
  for (const entry of fs.readdirSync(OUT_DIR)) {
    if (!entry.endsWith('.wgsl')) continue;

    const hasSource = fs.existsSync(path.join(SRC_DIR, entry));
    const hasLegacy = fs.existsSync(path.join(SHADERS_DIR, entry));

    if (!hasSource && !hasLegacy) {
      fs.unlinkSync(path.join(OUT_DIR, entry));
      console.log(`  ✗ ${entry}  (stale, removed)`);
    }
  }
}

function main() {
  console.log('\n🔧 WGSL Include Build\n');

  if (!fs.existsSync(OUT_DIR)) {
    fs.mkdirSync(OUT_DIR, { recursive: true });
  }

  // 1. Process source files with #include
  const srcFiles = fs.existsSync(SRC_DIR)
    ? fs.readdirSync(SRC_DIR).filter(f => f.endsWith('.wgsl'))
    : [];

  if (srcFiles.length === 0) {
    console.log('  (no .wgsl files in shaders/src/)');
  } else {
    console.log('Assembling from shaders/src/:');
    for (const f of srcFiles.sort()) {
      buildSourceFile(path.join(SRC_DIR, f));
    }
  }

  // 2. Copy standalone legacy shaders
  console.log('\nCopying legacy standalone shaders:');
  copyStandaloneLegacy();

  // 3. Remove stale outputs from previous runs
  console.log('\nCleaning stale outputs:');
  clearStaleOutputs();

  // 4. Summary
  const outCount = fs.readdirSync(OUT_DIR).filter(f => f.endsWith('.wgsl')).length;
  console.log(`\n✅ Done. ${outCount} .wgsl file(s) in public/shaders/\n`);
}

main();
